### ISSUE TITLE
Consider adding regions

### ISSUE THREAD

**Issue by MarkJaroski** [jakopako/croncert-web#29]
As some might say "Switzerland is a city, and the SBB/CFF is a métro". From Lausanne I have been known to range as far as Bern and Neuchatel for a good concert.

So it might be useful to consider some kind of regional functionality.

**Comment by jakopako** [comment]
Yeah that sounds useful. The goal would be to make searching easier right? So instead of having to search for Lausanne, then Bern, then Neuchatel etc. you'd just search for one region, right? 

Maybe having some kind of km radius would solve this issue? Or do you rather mean named regions, such as for instance any Kanton in Switzerland?

**Comment by MarkJaroski** [comment]
It's not obvious, I guess. The Kanton idea is cool, but I was thinking more of a super-regional thing. Maybe just doing a radius thing might be good (but difficult).

The user can always figure out the CFF or designated driver time using some other tool.

**Comment by jakopako** [comment]
The radius thing should be working now. Let me know if you encounter any issues or bugs. Closing this issue for now.
